# Generated by Django 4.2.17 on 2026-02-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
